language: php

sudo: false

php:
    - 7.1
    - 7.2
    - 7.3
#    - 7.4 # needs new version of PHPUnit because of deprecations in reflection when building mock objects
#    - 8.0 # need to specify php version differently in composer.json ^7.1 does not allow 8

matrix:
    fast_finish: true

services:
    - mongodb
    - mysql

env:
    - SYMFONY_VERSION=4.0.* DB=pdo_mysql DB_USER=root DB_NAME=lexik_test DEPENDENCIES=alpha
    - SYMFONY_VERSION=4.4.* DB=pdo_mysql DB_USER=root DB_NAME=lexik_test DEPENDENCIES=alpha
cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
    - if [ "$DEPENDENCIES" = "alpha" ]; then composer config minimum-stability alpha; fi;
    - if [ -x .travis/before_install.sh ]; then .travis/before_install.sh; fi;

install:
    - if [ -x .travis/install.sh ]; then .travis/install.sh; fi;

script:
    - php vendor/bin/phpunit -v
